# -*- coding: utf-8 -*-
"""thesis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ImmN9cFBiUM8Qe8Id9TBE7avjEdguhXz
"""

from google.colab import drive
drive.mount('/content/drive')

"""Libraries"""

!pip install -q sentence-transformers faiss-cpu
import math
import re
from collections import Counter, defaultdict
from pathlib import Path
from typing import List
import pandas as pd
import numpy as np
import faiss
from sentence_transformers import SentenceTransformer

"""1. Data loading + cleanup"""

def load_equipment_file(path: str) -> pd.DataFrame:
    suffix = Path(path).suffix.lower()

    if suffix == ".csv":
        df = pd.read_csv(path)
    elif suffix in [".xlsx", ".xls"]:
        df = pd.read_excel(path)
    else:
        raise ValueError(f"Unsupported file type: {suffix}")

    df = df.fillna("")

    # Keep only useful columns if they exist
    wanted_cols = [
        "Equipment name",
        "Aliases / synonyms",
        "Short description (2-3 sentences)",
        "Typical applications (3+ bullets)",
        "Research-oriented use (1-2 example study scenarios)",
        "Inputs",
        "Outputs",
        "Tags (5-10 keywords)",
        "Safety/training notes (if relevant)",
        "Source link(s)",
        "Confidence",
        "Confidence note",
        "University",
        "Authors / lab contacts",
    ]

    existing = [c for c in wanted_cols if c in df.columns]
    df = df[existing].copy()

    for col in df.columns:
        df[col] = df[col].astype(str).str.strip()

    return df

"""2. Text preprocessing"""

TOKEN_PATTERN = re.compile(r"[a-z0-9\-]+")

SYNONYM_MAP = {
    "gcms": "gc-ms",
    "ftir": "ft-ir",
    "sem": "scanning electron microscope",
    "tem": "transmission electron microscope",
    "hplc": "high performance liquid chromatography",
    "uvvis": "uv-vis",
    "xrd": "x-ray diffraction",
    "afm": "atomic force microscopy",
}

def normalize_text(text: str) -> str:
    text = str(text).lower().strip()

    # basic normalization
    text = text.replace("/", " ")
    text = text.replace("_", " ")
    text = text.replace("–", "-").replace("—", "-")

    for short, full in SYNONYM_MAP.items():
        text = re.sub(rf"\b{re.escape(short)}\b", full, text)

    return text


def tokenize(text: str) -> List[str]:
    text = normalize_text(text)
    return TOKEN_PATTERN.findall(text)

"""3. Weighted document builder"""

def weighted_concat(row: pd.Series) -> str:
    def repeat(text: str, n: int) -> str:
        text = str(text).strip()
        return ((text + " ") * n).strip() if text else ""

    name = row.get("Equipment name", "")
    aliases = row.get("Aliases / synonyms", "")
    desc = row.get("Short description (2-3 sentences)", "")
    apps = row.get("Typical applications (3+ bullets)", "")
    research = row.get("Research-oriented use (1-2 example study scenarios)", "")
    inputs = row.get("Inputs", "")
    outputs = row.get("Outputs", "")
    tags = row.get("Tags (5-10 keywords)", "")

    # Higher weight by repetition for important fields
    parts = [
        repeat(name, 4),
        repeat(aliases, 3),
        repeat(tags, 3),
        repeat(desc, 2),
        repeat(apps, 2),
        repeat(research, 1),
        repeat(inputs, 2),
        repeat(outputs, 2),
    ]
    return " ".join(p for p in parts if p).strip()

"""4. Simple BM25 implementation"""

class BM25Retriever:
    def __init__(self, documents: List[str], k1: float = 1.5, b: float = 0.75):
        self.k1 = k1
        self.b = b
        self.documents = [tokenize(doc) for doc in documents]
        self.doc_lens = [len(doc) for doc in self.documents]
        self.avgdl = sum(self.doc_lens) / max(len(self.doc_lens), 1)

        self.term_freqs = []
        self.doc_freqs = defaultdict(int)

        for doc in self.documents:
            freqs = Counter(doc)
            self.term_freqs.append(freqs)
            for term in freqs:
                self.doc_freqs[term] += 1

        self.N = len(self.documents)
        self.idf = {}
        for term, df in self.doc_freqs.items():
            # BM25 idf
            self.idf[term] = math.log(1 + (self.N - df + 0.5) / (df + 0.5))

    def score(self, query: str) -> List[float]:
        q_terms = tokenize(query)
        scores = []

        for i, freqs in enumerate(self.term_freqs):
            dl = self.doc_lens[i]
            score = 0.0
            for term in q_terms:
                if term not in freqs:
                    continue
                tf = freqs[term]
                idf = self.idf.get(term, 0.0)
                denom = tf + self.k1 * (1 - self.b + self.b * dl / self.avgdl)
                score += idf * (tf * (self.k1 + 1)) / denom
            scores.append(score)

        return scores

"""5. Metadata boosts"""

def overlap_count(query_terms: List[str], field_text: str) -> int:
    field_terms = set(tokenize(field_text))
    return sum(1 for t in query_terms if t in field_terms)


def confidence_boost(confidence: str) -> float:
    c = str(confidence).lower().strip()
    if c == "high":
        return 0.15
    if c == "medium":
        return 0.05
    return 0.0


def rerank_scores(df: pd.DataFrame, query: str, bm25_scores: List[float]) -> List[float]:
    q_terms = tokenize(query)
    final_scores = []

    max_bm25 = max(bm25_scores) if bm25_scores and max(bm25_scores) > 0 else 1.0

    for idx, row in df.iterrows():
        base = bm25_scores[idx] / max_bm25

        name = row.get("Equipment name", "")
        tags = row.get("Tags (5-10 keywords)", "")
        aliases = row.get("Aliases / synonyms", "")
        inputs = row.get("Inputs", "")
        outputs = row.get("Outputs", "")
        confidence = row.get("Confidence", "")

        exact_name = 0.0
        norm_name = normalize_text(name)
        norm_query = normalize_text(query)

        if norm_query in norm_name or norm_name in norm_query:
            exact_name += 0.35

        tag_boost = 0.04 * overlap_count(q_terms, tags)
        alias_boost = 0.03 * overlap_count(q_terms, aliases)
        io_boost = 0.03 * overlap_count(q_terms, inputs) + 0.03 * overlap_count(q_terms, outputs)
        conf_boost = confidence_boost(confidence)

        final = base + exact_name + tag_boost + alias_boost + io_boost + conf_boost
        final_scores.append(final)

    return final_scores

"""6. Recommender wrapper"""

class EquipmentRecommender:
    def __init__(self, df: pd.DataFrame):
        self.df = df.copy()
        self.df["search_text"] = self.df.apply(weighted_concat, axis=1)
        self.retriever = BM25Retriever(self.df["search_text"].tolist())

    def search(self, query: str, top_k: int = 10) -> pd.DataFrame:
        bm25_scores = self.retriever.score(query)
        final_scores = rerank_scores(self.df, query, bm25_scores)

        out = self.df.copy()
        out["bm25_score"] = bm25_scores
        out["final_score"] = final_scores

        out = out.sort_values(["final_score", "bm25_score"], ascending=False).head(top_k)

        columns_to_return = [
            "Equipment name",
            "Aliases / synonyms",
            "Short description (2-3 sentences)",
            "Tags (5-10 keywords)",
            "Inputs",
            "Outputs",
            "University",
            "Confidence",
            "bm25_score",
            "final_score",
        ]

        existing = [c for c in columns_to_return if c in out.columns]
        return out[existing]

def filter_equipment_rows(df: pd.DataFrame) -> pd.DataFrame:
    bad_name_terms = {
        "project", "size", "dose", "nanostructure", "probe tip"
    }

    def looks_like_equipment(row: pd.Series) -> bool:
        name = str(row.get("Equipment name", "")).lower().strip()
        desc = str(row.get("Short description (2-3 sentences)", "")).lower().strip()
        tags = str(row.get("Tags (5-10 keywords)", "")).lower().strip()

        if not name:
            return False

        # obvious non-equipment names
        if any(term == name or f" {term}" in f" {name}" for term in bad_name_terms):
            return False

        # prefer rows that look like actual instruments/devices/systems/microscopes/etc.
        equipment_keywords = [
            "microscope", "spectrometer", "analyzer", "instrument", "detector",
            "chromatograph", "sensor", "counter", "probe", "scanner", "meter",
            "sampler", "reactor", "balance", "centrifuge", "tensiometer"
        ]

        has_equipment_signal = (
            any(k in name for k in equipment_keywords) or
            any(k in desc for k in equipment_keywords) or
            any(k in tags for k in equipment_keywords)
        )

        return has_equipment_signal

    return df[df.apply(looks_like_equipment, axis=1)].reset_index(drop=True)

"""Semantic Search (vector)"""

class FaissVectorRetriever:
    def __init__(self, documents: List[str], model_name: str = "all-MiniLM-L6-v2"):
        self.model = SentenceTransformer(model_name)

        embeddings = self.model.encode(
            documents,
            convert_to_numpy=True,
            normalize_embeddings=True,
            show_progress_bar=True,
        ).astype("float32")

        self.embeddings = embeddings
        dim = embeddings.shape[1]

        self.index = faiss.IndexFlatIP(dim)
        self.index.add(embeddings)

    def score(self, query: str, top_k: int | None = None) -> List[float]:
        query_vec = self.model.encode(
            [query],
            convert_to_numpy=True,
            normalize_embeddings=True,
        ).astype("float32")

        if top_k is None:
            top_k = self.embeddings.shape[0]

        scores, indices = self.index.search(query_vec, top_k)

        out = np.zeros(self.embeddings.shape[0], dtype=np.float32)
        for score, idx in zip(scores[0], indices[0]):
            if idx != -1:
                out[idx] = float(score)

        return out.tolist()

"""Reranking"""

def overlap_count(query_terms: List[str], field_text: str) -> int:
    field_terms = set(tokenize(field_text))
    return sum(1 for t in query_terms if t in field_terms)


def confidence_boost(confidence: str) -> float:
    c = str(confidence).lower().strip()
    if c == "high":
        return 0.15
    if c == "medium":
        return 0.05
    return 0.0


def rerank_scores(
    df: pd.DataFrame,
    query: str,
    bm25_scores: List[float],
    vector_scores: List[float] | None = None,
    bm25_weight: float = 0.6,
    vector_weight: float = 0.4,
) -> List[float]:
    q_terms = tokenize(query)
    final_scores = []

    max_bm25 = max(bm25_scores) if bm25_scores and max(bm25_scores) > 0 else 1.0

    if vector_scores is None:
        vector_scores = [0.0] * len(bm25_scores)
        vector_weight = 0.0
        bm25_weight = 1.0

    max_vec = max(vector_scores) if vector_scores and max(vector_scores) > 0 else 1.0

    for idx, row in df.iterrows():
        bm25_norm = bm25_scores[idx] / max_bm25
        vec_norm = vector_scores[idx] / max_vec if max_vec > 0 else 0.0

        hybrid_base = bm25_weight * bm25_norm + vector_weight * vec_norm

        name = row.get("Equipment name", "")
        tags = row.get("Tags (5-10 keywords)", "")
        aliases = row.get("Aliases / synonyms", "")
        inputs = row.get("Inputs", "")
        outputs = row.get("Outputs", "")
        confidence = row.get("Confidence", "")

        exact_name = 0.0
        norm_name = normalize_text(name)
        norm_query = normalize_text(query)

        if norm_query in norm_name or norm_name in norm_query:
            exact_name += 0.35

        tag_boost = 0.04 * overlap_count(q_terms, tags)
        alias_boost = 0.03 * overlap_count(q_terms, aliases)
        io_boost = 0.03 * overlap_count(q_terms, inputs) + 0.03 * overlap_count(q_terms, outputs)
        conf_boost = confidence_boost(confidence)

        final = hybrid_base + exact_name + tag_boost + alias_boost + io_boost + conf_boost
        final_scores.append(final)

    return final_scores

"""Hybrid recommender"""

class HybridEquipmentRecommender:
    def __init__(self, df: pd.DataFrame, embedding_model: str = "all-MiniLM-L6-v2"):
        self.df = df.copy()
        self.df["search_text"] = self.df.apply(weighted_concat, axis=1)

        docs = self.df["search_text"].tolist()

        self.bm25 = BM25Retriever(docs)
        self.vector = FaissVectorRetriever(docs, model_name=embedding_model)

    def search(self, query: str, top_k: int = 10) -> pd.DataFrame:
        bm25_scores = self.bm25.score(query)
        vector_scores = self.vector.score(query)

        final_scores = rerank_scores(
            self.df,
            query,
            bm25_scores,
            vector_scores,
            bm25_weight=0.6,
            vector_weight=0.4,
        )

        out = self.df.copy()
        out["bm25_score"] = bm25_scores
        out["vector_score"] = vector_scores
        out["final_score"] = final_scores

        out = out.sort_values(["final_score", "bm25_score", "vector_score"], ascending=False).head(top_k)
        return out[
            [
                "Equipment name",
                "Aliases / synonyms",
                "Short description (2-3 sentences)",
                "Tags (5-10 keywords)",
                "Inputs",
                "Outputs",
                "University",
                "Confidence",
                "bm25_score",
                "vector_score",
                "final_score",
            ]
        ]

"""7. Example usage"""

if __name__ == "__main__":
    path = "/content/drive/MyDrive/Thesis/equipment_database.csv"
    df = load_equipment_file(path)

    system = HybridEquipmentRecommender(df)

    queries = [
        "I need equipment for air quality measurements in a lab",
        "instrument for surface imaging at nanoscale",
        "measure trace metals in water samples",
        "tool for infrared spectroscopy of polymers",
    ]

    for q in queries:
        print(f"\nQUERY: {q}")
        print(system.search(q, top_k=5).to_string(index=False))

if __name__ == "__main__":
    path = "/content/drive/MyDrive/Thesis/equipment_database.csv"
    df = load_equipment_file(path)
    df = filter_equipment_rows(df)

    system = EquipmentRecommender(df)

    example_queries = [
        "I need equipment for air quality measurements in a lab",
        "instrument for surface imaging at nanoscale",
        "measure trace metals in water samples",
        "tool for infrared spectroscopy of polymers",
    ]

    for q in example_queries:
        print(f"\nQUERY: {q}")
        results = system.search(q, top_k=5)
        print(results.to_string(index=False))